<img id="top" src="images/top.png" alt="">
<div id="form_container">

    <h1><a>WZM-DB</a></h1>
    <form id="form_816263" class="appnitro"  method="post" action="?goto=insert2">
        <div class="form_description">
            <h2>WZM Hinzufügen</h2>
            <p>Datenbankzugriff auf die DB WZM</p>
        </div>                        
        <ul >

            <li id="li_1" >
            <label class="description" for="element_1">Maschinentyp </label>
            <div>
                <select class="element select medium" id="element_1" name="Typ_em"> 
                        
<?php
    // Session-Nutzung, um die zuletzt ausgewählten Elemente in den Select-Feldern zu aktivieren!
    session_name("sop");
    session_start();

    include_once("include/connect_to_database.inc.php");
    $dblink = connect_to_database("mbi");

    $query =  "SELECT TypNr, MTyp FROM Maschinentyp order by MTyp";
    $result = mysqli_query($dblink, $query);
    if ($result != false) {
        while($row = mysqli_fetch_row($result)) {
            echo "<option value=$row[0]>"; //TypNr wir übergeben
            // Aktivieren der letzten Auswahl, falls vorhanden
            if (isset($_SESSION["Typ_em"]) && $_SESSION["Typ_em"] == $row[1]) {
                echo " selected";
            }
            echo ">".htmlentities($row[1])."</option>"; //MTyp wird in die Liste geschrieben
        }
    }
?>
                </select>
            </div> 
            </li>
            
            <li id="li_2" >
            <label class="description" for="element_2">Standort </label>
            <input type="text" name="Ort_e" required>
            </li>
          
            <li id="li_3" >
            <label class="description" for="element_3">Wartungsintervall </label>
            <input type="text" name="myInput" 
                onkeypress="return numbersOnly(this, event);" 
                onpaste="return false;" />
            </li>
            
            <li class="buttons">
            <input type="hidden" name="form_id" value="816263" />

            <input id="saveForm" class="button_text" type="submit" name="submit" value="Absenden" />
            </li>
        </ul>
    </form>    
    <div id="footer">
        Generated by <a href="http://www.phpform.org">pForm</a>
    </div>
</div>
<img id="bottom" src="images/bottom.png" alt="">

<script>
// geklaut von stackoverflow: 
// https://stackoverflow.com/questions/891696/jquery-what-is-the-best-way-to-restrict-number-only-input-for-textboxes-all
  function numbersOnly(oToCheckField, oKeyEvent) {
    return oKeyEvent.charCode === 0 ||
        /\d/.test(String.fromCharCode(oKeyEvent.charCode));
  }
</script>
