<img id="top" src="images/top.png" alt="">
<div id="form_container">

    <h1><a>WZM-DB</a></h1>
    <form id="form_816263" class="appnitro"  method="post" action="?goto=insert1">
        <div class="form_description">
            <h2>WZM-Typ Hinzufügen</h2>
            <p>Datenbankzugriff auf die DB WZM</p>
        </div>                        
        <ul >

            <li id="li_1" >
            <div>  
            </li>
            <li id="li_2" >
            <label class="description" for="element_1">Maschinentyp </label>
            <input type="text" name="Typ_e" required>
            </li>
            <li class="buttons">
            <input type="hidden" name="form_id" value="816263" />

            <input id="saveForm" class="button_text" type="submit" name="submit" value="Absenden" />
            </li>
        </ul>
    </form>    
    <div id="footer">
        Generated by <a href="http://www.phpform.org">pForm</a>
    </div>
</div>
<img id="bottom" src="images/bottom.png" alt="">
