<img id="top" src="images/top.png" alt="">
<div id="form_container">

    <h1><a>WZM-DB</a></h1>
    <form id="form_816263" class="appnitro"  method="post" action="?goto=query1">
        <div class="form_description">
            <h2>WZM-Übersicht</h2>
            <p>Datenbankzugriff auf die DB WZM</p>
        </div>                        
        <ul >

            <li id="li_1" >
            <label class="description" for="element_1">Maschinentyp </label>
            <div>
                <select class="element select medium" id="element_1" name="Typ_u"> 
                        
<?php
    // Session-Nutzung, um die zuletzt ausgewählten Elemente in den Select-Feldern zu aktivieren!
    session_name("sop");
    session_start();

    include_once("include/connect_to_database.inc.php");
    $dblink = connect_to_database("mbi");

    $query =  "SELECT TypNr, MTyp FROM Maschinentyp order by MTyp";
    $result = mysqli_query($dblink, $query);
    if ($result != false) {
        echo "<option value=0";
        if (!isset($_SESSION["Typ"]) || $_SESSION["Typ"] == 0) {
            echo " selected";
        }
        echo ">alle</option>";

        while($row = mysqli_fetch_row($result)) {
            echo "<option value=$row[0]>"; //TypNr wir übergeben
            // Aktivieren der letzten Auswahl, falls vorhanden
            if (isset($_SESSION["Typ"]) && $_SESSION["Typ"] == $row[1]) {
                echo " selected";
            }
            echo ">".htmlentities($row[1])."</option>"; //MTyp wird in die Liste geschrieben
        }
    }
?>
                </select>
            </div> 
            </li>

            <li class="buttons">
            <input type="hidden" name="form_id" value="816263" />

            <input id="saveForm" class="button_text" type="submit" name="submit" value="Absenden" />
            </li>
        </ul>
    </form>    
    <div id="footer">
        Generated by <a href="http://www.phpform.org">pForm</a>
    </div>
</div>
<img id="bottom" src="images/bottom.png" alt="">
